services:
  localstack:
    image: nahuelnucera/ministack:latest
    networks:
      - hmpps
    ports:
      - "4566:4566"

  person-location-db:
    image: postgres
    networks:
      - hmpps
    container_name: person-location-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=person_location
      - POSTGRES_USER=person
      - POSTGRES_PASSWORD=l0c4710n

networks:
  hmpps:
