generic-service:

  ingress:
    host: person-location-api-preprod.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: preprod
    SENTRY_ENVIRONMENT: preprod

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: move-and-improve-alerts-non-prod
  rdsAlertsDatabases:
    cloud-platform-02de43ec94984c2f: "Person Location API DB"
    rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-person-location-preprod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-person-location-preprod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15