generic-service:

  ingress:
    host: person-location-api-dev.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: dev
    SENTRY_ENVIRONMENT: dev

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: move-and-improve-alerts-non-prod
  rdsAlertsDatabases:
    cloud-platform-6121b9f1d74f5509: "Person Location API DB"
    rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-person-location-dev-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-person-location-dev-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15