generic-service:
  ingress:
    host: person-location-api.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: prod
    SENTRY_ENVIRONMENT: prod

generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
  rdsAlertsDatabases:
    cloud-platform-7a12990ca37ce3af: "Person Location API DB"
    rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-person-location-prod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-person-location-prod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
